# intro
Here is the manual for sparse matrices in python: <br>
https://docs.scipy.org/doc/scipy/reference/sparse.html

Here is the manual for sparse linear algebra in python: <br>
https://docs.scipy.org/doc/scipy/reference/sparse.linalg.html

In this notebook we test sparse function that we probably need.

In [54]:
from scipy.sparse import eye
from scipy.sparse import diags
from scipy.sparse.linalg import inv

n = 5
I = 5*eye(n)
P = diags([-1,2,-1],[-1,0,1],(n,n))
print(inv(I))
print(P.toarray())

  (0, 0)	0.2
  (1, 1)	0.2
  (2, 2)	0.2
  (3, 3)	0.2
  (4, 4)	0.2
[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


C:\Users\isido\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:168: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  warn('spsolve requires A be CSC or CSR matrix format',
C:\Users\isido\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:239: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '


The manual way is with the dok matrix, note that scipy automatically changes 
sparse type to csr for doing matrix multiplication. @ is short hand for matrix 
and vector multiplication.

In [48]:
from scipy.sparse import dok_matrix # for constructing matrices with for loops
import numpy as np
n = 5
M = dok_matrix((n, n))

for i in range(M.shape[0]):
    M[i,i]=2

for i in range(M.shape[0]-1):
    M[i,i+1]=-1

for i in range(M.shape[0]-1):
    M[i+1,i]=-1
print(M.toarray())
B = M @ M
print(type(B))

b = np.ones(n)
print(M@b)

[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]
<class 'scipy.sparse._csr.csr_matrix'>
[1. 0. 0. 0. 1.]


[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]
